### ISSUE TITLE
Question about ASRock Z590 Phantom Gaming-ITX/TB4

### ISSUE THREAD

**Issue by fabiensanglard** [petersulyok/asrock_z690_extreme#2]
Any trick to find out which I/O controller is used in the ASRock Z590 Phantom Gaming-ITX/TB4?

The documentation does not mention anything. https://download.asrock.com/Manual/X570%20Phantom%20Gaming-ITXTB3.pdf

Alternatively, I would take any trick that helps me to figure out what correspond to ID 0xd441

```
$ sensors-detect
Trying family `VIA/Winbond/Nuvoton/Fintek'...               Yes
Found unknown chip with ID 0xd441
```

**Comment by petersulyok** [comment]
Pictures about the motherboard can tell a lot. I found [this review](https://www.techpowerup.com/review/asrock-z690-phantom-gaming-itx-tb4/) and this picture: 

![](https://www.techpowerup.com/review/asrock-z690-phantom-gaming-itx-tb4/images/chipset.jpg)

Based on this it seems that your Super IO chip is Nuvoton NCT6686D. [This conversation](https://lore.kernel.org/linux-hwmon/20210311215055.GA36492@roeck-us.net/T/) is showing that your SIO is supported by the [nct6683 kernel module](https://docs.kernel.org/hwmon/nct6683.html), but it has to be forced at loading.

If you are not able to load this module, you may ask Guenter Roeck <[linux@roeck-us.net](mailto:linux%40roeck-us.net)>, the author of this module, he might be interested in testing the module on a new hardware.

If the module is loaded properly you can start the configuration (check voltage, temperature and fan sensors in the BIOS, and in `lm-sensors`) and you can also check the ASRock ATUNING utility (XML config file) in Windows to understand the mapping.

**Comment by petersulyok** [comment]
Opps, I missed the motherboard version, but checked again and the result is the same.
Here is the proper [review](https://www.techpowerup.com/review/asrock-z590-phantom-gaming-itx-tb4/), and picture:

![](https://www.techpowerup.com/review/asrock-z590-phantom-gaming-itx-tb4/images/fan-control.jpg)

Let me know if you are on track.
